### ISSUE TITLE
Does not work for suspended, overdue, review sibling cards.

### ISSUE THREAD

**Issue by BaekToDaFuture** [lovac42/TheRoommateSwitch#1]
I have a deck that has been long overdue. I unsuspended "card:1" in hopes to unsuspend siblings as I review the cards, but did not work. It works when I go into the browser, select the sibling and reset schedule to be a new card.

**Comment by lovac42** [comment]
This addon is used to swap new cards. Swapping sibling review cards will screw up the algorithm. I guess I should make that clear in the descriptions.
